---
title: "Hist_Euc"
author: "Divya"
date: "2023-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

#install.packages("randomcoloR")
library(plyr)
library(dplyr)
library(phyloseq)
library(randomcoloR)
```


### Preparing for the plots GENUS
```{r}
asv=read.table("/home/dpatel/sequences/Euc/euc_csv/rarefied_asv.csv", sep=",", row.names=1, header=TRUE, check.names=FALSE) 
taxa=read.table("/home/dpatel/sequences/Euc/euc_csv/rarefied_taxa.csv", sep=",", row.names=1, header=TRUE) 
meta=read.table("/home/dpatel/sequences/Euc/euc_csv/rarefied_meta.csv", sep=",", row.names=1, header=TRUE) 

# Merge into phyloseq object 
ps=phyloseq(otu_table(asv, taxa_are_rows=TRUE), tax_table(as.matrix(taxa)), sample_data(meta))

# Select taxonomic rank
taxa_rank="Genus"

# Transform counts to relative abundance and agglomerate to the desired taxonomic rank. Melt phyloseq object to dataframe. 
ps_rel_abund=transform_sample_counts(ps, function(x) x/sum(x)) # get abundance in %
glom=tax_glom(ps_rel_abund, taxrank = taxa_rank) # agglomerate taxa at the desired taxonomic level
df=psmelt(glom) # create dataframe from phyloseq object

medians=ddply(df, taxa_rank, function(x) c(median=median(x$Abundance)))
remainder <- medians[medians$median <= 0.001,][[1]] # Find taxons whose rel. abund. is less than 0.1%
df[df[[taxa_rank]] %in% remainder,][[taxa_rank]]="Other (abundance < 0.1%)" # Change their name to "Other (abondance < 0.1%)"

# Create empty list 
list_of_all_taxonomic_rank= list()

# Loop over every sample_type to combine taxons with a relative abundance < 0.5% 
data <- data.frame()

for (sample in unique(df$Sample)){
    table=subset(df, Sample==sample)
    medians=ddply(table, taxa_rank, function(x) c(median=median(x$Abundance)))
    remainder <- medians[medians$median <= 0.001,][[1]] # Find taxons whose rel. abund. is less than 0.1%
    table[table[[taxa_rank]] %in% remainder,][[taxa_rank]]="Other (abundance < 0.1%)" # Change their name to "Other (abondance < 0.1%)"
    list_of_all_taxonomic_rank <- append(list_of_all_taxonomic_rank,table[[taxa_rank]])
data = rbind(df,table)

taxon_list=as.data.frame(list_of_all_taxonomic_rank)
df_taxon_list=as.data.frame(t(taxon_list))
unique_taxonomic_ranks=as.data.frame(unique(df_taxon_list$V1))
names(unique_taxonomic_ranks)[names(unique_taxonomic_ranks)=="unique(df_taxon_list$V1)"]=as.character(taxa_rank) # Rename column 

}

## SET COLORS
# To create a new color range
unique_sources=data.frame(unique(df$Genus))
colors= c("#9E0000","#F66308","#099fb0","#BFD7EA","#3D405B","#cdb4db","#ffadc7","#A0785A", "#582f0e","#ADC178","#86626e","#8CCAC3")
my_scale=scale_fill_manual(name=as.character(unique_sources), values = colors, na.translate=FALSE, drop=FALSE, limits = force)

# Ok we have to seperate the Data between Filters and Rocks.
Genus_Filters <- df[(df$SampleType == "Filtre"), ]
Genus_Filters$Sample <- gsub("F-", "", Genus_Filters$Sample)
Genus_Filters$Sample <- gsub("-J", "-D", Genus_Filters$Sample)

# Change the names in the Bioreacteur column to Bioreactor 1, Bioreactor 2, Bioreactor 3 and Field
Genus_Filters$Bioreacteur <- ifelse(grepl("^B", Genus_Filters$Bioreacteur), "Bioreactor 1",
                        ifelse(grepl("^J", Genus_Filters$Bioreacteur), "Bioreactor 2",
                         ifelse(grepl("^R", Genus_Filters$Bioreacteur), "Bioreactor 3", "Field")))
Genus_Filters$Sample<- gsub("Tourb", "PB", Genus_Filters$Sample)

# Extract numbers from the end of Sample names and multiply by 2
Genus_Filters <- Genus_Filters %>%
  mutate(Sample = ifelse(Sample %in% c("P1", "P2", "P3", "P4"), Sample, str_replace(Sample, "(\\d+)$", function(match) as.character(2 * as.numeric(match)))))

```



##### Plot FOR FILTERS
```{r}

# Plot
Genus_Filters$Sample <- factor(Genus_Filters$Sample, c("P1","P2","P3","P4","PB",
                              "B-D2","B-D6","B-D10","B-D14","B-D18",
                              "J-D2","J-D4","J-D6","J-D10","J-D12","J-D14","J-D16","J-D18","J-D22",
                              "R-D4","R-D6","R-D10","R-D12","R-D14","R-D16","R-D18","R-D20")) 


Euc_Genus=ggplot(Genus_Filters, aes(x=Sample, weight=Abundance, fill=.data[[taxa_rank]])) +
  geom_bar() +
  labs(y ='Relative abundance (%)', paste(sample), x = "Planktonic samples", ) +
  scale_y_continuous(expand = c(0,0)) +
  theme(text = element_text(size = 20),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  my_scale + 
  guides(fill=guide_legend(title="Genus")) +
  facet_grid(cols = vars(Genus_Filters$Bioreacteur),scales="free", margins = FALSE, drop = F) +
  ggtitle(" ")
  
Euc_Genus
ggsave("/home/dpatel/sequences/Euc/euc_Figures/Euc_Filtre_Genus2.tiff", width = 24, height = 12, plot = last_plot())
```


# Plot for ROCKS
```{r}
# Plot
Genus_Rocks <- df[(df$SampleType == "Roche"),] 
Genus_Rocks$Sample <- gsub("R-", "", Genus_Rocks$Sample)

# Change the names in the Bioreacteur column to Bioreactor 1, Bioreactor 2, Bioreactor 3 and Field
Genus_Rocks$Bioreacteur <- ifelse(grepl("^B", Genus_Rocks$Bioreacteur), "Bioreactor 1",
                        ifelse(grepl("^J", Genus_Rocks$Bioreacteur), "Bioreactor 2",
                         ifelse(grepl("^R", Genus_Rocks$Bioreacteur), "Bioreactor 3", "Field")))

Genus_Rocks$Sample <- factor(Genus_Rocks$Sample, c("B1B","B5B","B7B","B8B","B3M","B4M","B1H","B6H","B7H",
                                                   "J1B","J3B","J7B","J8B","J2H","R5B","R7B","R2M","R3M","R7M","R1H"))

Euc_Genus=ggplot(Genus_Rocks, aes(x=Sample, weight=Abundance, fill=.data[[taxa_rank]])) +
  geom_bar() +
  labs(y ='Relative abundance (%)', paste(sample), x = "Sessile samples", ) +
  scale_y_continuous(expand = c(0,0)) +
  theme(text = element_text(size = 20),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  my_scale + 
  guides(fill=guide_legend(title="Genus")) +
  facet_grid(cols = vars(Genus_Rocks$Bioreacteur), scales="free", margins = FALSE, drop = F) +
  ggtitle(" ")
  
Euc_Genus
ggsave("/home/dpatel/sequences/Euc/euc_Figures/Euc_Roche_Genus.tiff", width = 24, height = 12, plot = last_plot())
```




