---
title: "Hist_arc"
author: "Divya"
date: "2023-01-15"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())

#install.packages("randomcoloR")
library(plyr)
library(dplyr)
library(phyloseq)
library(randomcoloR)
```


### Preparing for the plots GENUS
```{r}

asv=read.table("/home/dpatel/sequences/Arc/arc_csv/rarefied_asv.csv", sep=",", row.names=1, header=TRUE, check.names=FALSE) 
taxa=read.table("/home/dpatel/sequences/Arc/arc_csv/rarefied_taxa.csv", sep=",", row.names=1, header=TRUE) 
meta=read.table("/home/dpatel/sequences/Arc/arc_csv/rarefied_meta.csv", sep=",", row.names=1, header=TRUE) 

# Merge into phyloseq object 
ps=phyloseq(otu_table(asv, taxa_are_rows=TRUE), tax_table(as.matrix(taxa)), sample_data(meta))

# Select taxonomic rank
taxa_rank="genus"

# Transform counts to relative abundance and agglomerate to the desired taxonomic rank. Melt phyloseq object to dataframe. 
ps_rel_abund=transform_sample_counts(ps, function(x) x/sum(x)) # get abundance in %
glom=tax_glom(ps_rel_abund, taxrank = taxa_rank) # agglomerate taxa at the desired taxonomic level
df=psmelt(glom) # create dataframe from phyloseq object

medians=ddply(df, taxa_rank, function(x) c(median=median(x$Abundance)))
remainder <- medians[medians$median <= 0.001,][[1]] # Find taxons whose rel. abund. is less than 0.1%
df[df[[taxa_rank]] %in% remainder,][[taxa_rank]]="Other (abundance < 0.1%)" # Change their name to "Other (abondance < 0.1%)"


# Create empty list 
list_of_all_taxonomic_rank= list()

# Loop over every sample_type to combine taxons with a relative abundance < 0.1% 
data <- data.frame()

for (sample in unique(df$Sample)){
    table=subset(df, Sample==sample)
    medians=ddply(table, taxa_rank, function(x) c(median=median(x$Abundance)))
    remainder <- medians[medians$median <= 0.001,][[1]] # Find taxons whose rel. abund. is less than 0.1%
    table[table[[taxa_rank]] %in% remainder,][[taxa_rank]]="Other (abundance < 0.1%)" # Change their name to "Other (abondance < 0.1%)"
    list_of_all_taxonomic_rank <- append(list_of_all_taxonomic_rank,table[[taxa_rank]])
data = rbind(df,table)

taxon_list=as.data.frame(list_of_all_taxonomic_rank)
df_taxon_list=as.data.frame(t(taxon_list))
unique_taxonomic_ranks=as.data.frame(unique(df_taxon_list$V1))
names(unique_taxonomic_ranks)[names(unique_taxonomic_ranks)=="unique(df_taxon_list$V1)"]=as.character(taxa_rank) # Rename column 
}

```



##### Plot GENUS FOR FILTER
```{r}
## SET COLORS
# To create a new color range
unique_sources=data.frame(unique(df$Genus))
colors= c("#9E0000","#F24D3C","#F9853D","#FCCA46","#A1C181","#17633F","#0a9396","#BFD7EA","#444054","#F3E3E2","#AF75A0","#89023E", "#ffadc7", "#582f0e","#A0785A","#F2CC8F","#BEBBBB","#554640")
my_scale=scale_fill_manual(name=as.character(unique_sources), values = colors, na.translate=FALSE, drop=FALSE, limits = force)

df$Bioreacteur <- ifelse(grepl("^Bleu", df$Bioreacteur), "Bioreactor 1",
                        ifelse(grepl("^Jaune", df$Bioreacteur), "Bioreactor 2",
                         ifelse(grepl("^Rouge", df$Bioreacteur), "Bioreactor 3", "Field")))


# Plot
df$Sample <- gsub("F-", "", df$Sample)
df$Sample <- gsub("-J", "-D", df$Sample)

# Extract numbers from the end of Sample names and multiply by 2
df <- df %>%
  mutate(Sample = ifelse(Sample %in% c("P1", "P2", "P3", "P4"), Sample, str_replace(Sample, "(\\d+)$", function(match) as.character(2 * as.numeric(match)))))

df$Sample<- gsub("Tourb", "PB", df$Sample)

df$Sample <- factor(df$Sample, c("P1","P2","P3","P4","PB",
                              "B-D2","B-D6","B-D8","B-D14","B-D18",
                              "J-D4","J-D8","J-D10","J-D12","J-D14","J-D18",
                              "R-D4","R-D6","R-D8","R-D10","R-D12","R-D14","R-D16","R-D18","R-D20")) 

Arc_Genus=ggplot(df, aes(x=Sample, weight=Abundance, fill=.data[[taxa_rank]])) +
  geom_bar() +
  labs(y ='Relative abundance (%)', paste(sample), x = "Planktonic samples", ) +
  scale_y_continuous(expand = c(0,0)) +
  theme(text = element_text(size = 20),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  my_scale + 
  guides(fill=guide_legend(title="Genus")) +
  facet_grid(cols = vars(df$Bioreacteur),scales="free", margins = FALSE, drop = F) +
  ggtitle(" ")
  
Arc_Genus
ggsave("/home/dpatel/sequences/Arc/arc_Figures/Arc_Filtre_Genus2.tiff", width = 24, height = 12, plot = last_plot())

```


### Checking the abundance of each taxa
```{r}
# Create a function to calculate percentage and combine dataframes
calculate_percentage <- function(df) {
  df$Percentage <- (df$Abundance / sum(df$Abundance)) * 100
  return(df)
}

# List of Bioreactor 
bioreactor_values <- c("Bioreactor 1", "Bioreactor 2", "Bioreactor 3")

# Naming the dataframe for the for loop
combined_dfs <- list()

# Doing the for loop
for (bioreactor_value in bioreactor_values) {
  bio_filter <- df[df$Bioreacteur == bioreactor_value, ]
  agg <- aggregate(Abundance ~ genus + Jour, data = bio_filter, FUN = sum)
  split_dfs <- split(agg, agg$Jour)
  
# Calculate percentage for each dataframe
  split_dfs <- lapply(split_dfs, calculate_percentage)
  
# Combine the dataframes 
  combined_df <- do.call(rbind, split_dfs)
  combined_dfs[[bioreactor_value]] <- combined_df
}

# Combine dataframes from different bioreactors
final_combined_df <- do.call(rbind, combined_dfs)

# Print the final combined dataframe
final_combined_df


```




###===============================================|PHYLUM|===============================================###






### Preparing for the plots PHYLUM
```{r}
rm(list=ls())

asv=read.table("/home/dpatel/sequences/Arc/arc_csv/rarefied_asv.csv", sep=",", row.names=1, header=TRUE, check.names=FALSE) 
taxa=read.table("/home/dpatel/sequences/Arc/arc_csv/rarefied_taxa.csv", sep=",", row.names=1, header=TRUE) 
meta=read.table("/home/dpatel/sequences/Arc/arc_csv/rarefied_meta.csv", sep=",", row.names=1, header=TRUE) 

# Merge into phyloseq object 
ps=phyloseq(otu_table(asv, taxa_are_rows=TRUE), tax_table(as.matrix(taxa)), sample_data(meta))

# Select taxonomic rank
taxa_rank="phylum"

# Transform counts to relative abundance and agglomerate to the desired taxonomic rank. Melt phyloseq object to dataframe. 

ps_rel_abund=transform_sample_counts(ps, function(x) x/sum(x)) # get abundance in %
glom=tax_glom(ps_rel_abund, taxrank = taxa_rank) # agglomerate taxa at the desired taxonomic level
df=psmelt(glom) # create dataframe from phyloseq object


# Create empty list 
list_of_all_taxonomic_rank= list()

# Loop over every sample_type to combine taxons with a relative abundance < 0.1% 
data <- data.frame()

for (sample in unique(df$Sample)){
    table=subset(df, Sample==sample)
    medians=ddply(table, taxa_rank, function(x) c(median=median(x$Abundance)))
    remainder <- medians[medians$median <= 0.001,][[1]] # Find taxons whose rel. abund. is less than 0.1%
    table[table[[taxa_rank]] %in% remainder,][[taxa_rank]]="Other (abundance < 0.1%)" # Change their name to "Other (abondance < 0.1%)"
    list_of_all_taxonomic_rank <- append(list_of_all_taxonomic_rank,table[[taxa_rank]])
data = rbind(df,table)

taxon_list=as.data.frame(list_of_all_taxonomic_rank)
df_taxon_list=as.data.frame(t(taxon_list))
unique_taxonomic_ranks=as.data.frame(unique(df_taxon_list$V1))
names(unique_taxonomic_ranks)[names(unique_taxonomic_ranks)=="unique(df_taxon_list$V1)"]=as.character(taxa_rank) # Rename column 

}


```



##### Plot PHYLUM for FILTERS
```{r}

## SET COLORS
# To create a new color range
unique_sources=data.frame(unique(df$Phylum))
colors= c("#582f0e","#F3E3E2","#AF75A0","#444054","#BFD7EA","#0a9396","#17633F","#83B167","#FDB750","#F24D3C","#89023E","#F2CC8F")
my_scale=scale_fill_manual(name=as.character(unique_sources), values = colors, na.translate=FALSE, drop=FALSE, limits = force)


# Plot

df$Sample <- gsub("F-", "", df$Sample)

df$Sample <- factor(df$Sample, c("P1","P2","P3","P4","Tourb",
                              "B-J1","B-J3","B-J4","B-J7",
                              "J-J2","J-J4","J-J5","J-J6","J-J7","J-J9",
                              "R-J2","R-J3","R-J4","R-J5","R-J6","R-J7","R-J8","R-J9","R-J10")) 

Arc_Phylum=ggplot(df, aes(x=Sample, weight=Abundance, fill=.data[[taxa_rank]])) +
  geom_bar() +
  labs(y ='Relative abundance (%)', paste(sample), x = "Filter", ) +
  scale_y_continuous(expand = c(0,0)) +
  theme(text = element_text(size = 20),axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  my_scale + 
  guides(fill=guide_legend(title="Phylum")) +
  facet_grid(cols = vars(df$Bioreacteur), scales="free", margins = FALSE, drop = F) +
  ggtitle(" ")
  
  
Arc_Phylum
ggsave("sequences/Arc/arc_Figures/Arc_Filtre_Phylum.pdf", width = 24, height = 12, plot = last_plot())


```

